let g:mapleader=","

" SHORTCUTS
" window shortcut
nnoremap <leader>w <C-w>
" redo shortcut
nmap <leader>cr <C-r>

" MOVEMENT KEYMAPS
nmap <leader>cd <C-d> " go up
nmap <leader>cu <C-u> " go down
nmap ff mfgggqG`f " format file

" BUFFER KEYMAPS
nmap <leader><leader> :ls<cr>:b<space> " open buffer list
nmap <leader>bp :bp<cr> " previous buffer
nmap <leader>bn :bn<cr> " next buffer

" SPECIAL OPTIONS
" remember last line when opening
augroup vimStartup
	autocmd!
	autocmd BufReadPost *
		\ let line = line("'\"")
		\ | if line >= 1 && line <= line("$") && &filetype !~# 'commit'
		\      && index(['xxd', 'gitrebase'], &filetype) == -1
		\ |   execute "normal! g`\""
		\ | endif
augroup END

" GENERAL OPTIONS
set nocompatible
set ruler
set showcmd
set ttimeout
set ttimeoutlen=100
set display=truncate
set scrolloff=5
set incsearch
set nrformats-=octal
filetype plugin indent on
syntax on
let c_comment_strings=1
set nolangremap
set matchtime=0 ic nu
set laststatus=2
set nohlsearch
set mouse=a
set autoindent smartindent

" WHITESPACE HIGHLIGHTING
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" STYLE
set ts=8 sw=8 sts=8 cc=80 tw=79 noexpandtab
set cino=t0,l1,:0
autocmd BufEnter *.md set ft=pandoc
autocmd BufEnter *.html,*.css,*.js set ts=4 sts=4 sw=4
let g:html_indent_inctags = "head,body,p"

" COLOR
let g:gruvbox_contrast_dark="hard"
colo gruvbox

" WEB
command Web :!firefox %

" COC
source $MYVIMDIR/coc.vim

" NETRW
nnoremap <leader>l :Lex<cr>
let g:netrw_banner = 0
let g:netrw_winsize = 25
let g:netrw_liststyle = 3
let g:netrw_localcopydircmd = 'cp -r'
let g:netrw_browse_split = 2
set splitright
